#if !canImport(ObjectiveC)
import XCTest

extension StunClientIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StunClientIntegrationTests = [
        ("testServerDoesntAnswer", testServerDoesntAnswer),
        ("testServerReturnError", testServerReturnError),
        ("testSuccessfullAnswer", testSuccessfullAnswer),
    ]
}

extension StunMessageTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StunMessageTypeTests = [
        ("testFromCorrectData", testFromCorrectData),
        ("testFromEmptyData", testFromEmptyData),
        ("testFromWrongData", testFromWrongData),
        ("testToData", testToData),
    ]
}

extension StunPacketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StunPacketTests = [
        ("testIfResponseIsCorrectFailed", testIfResponseIsCorrectFailed),
        ("testIfResponseIsCorrectFailedTransactionId", testIfResponseIsCorrectFailedTransactionId),
        ("testIfResponseIsCorrectSuccess", testIfResponseIsCorrectSuccess),
        ("testParseAttributesFromCorrectData", testParseAttributesFromCorrectData),
        ("testParsePacketFromCorrectBuffer", testParsePacketFromCorrectBuffer),
        ("testParsePacketFromCorrectData", testParsePacketFromCorrectData),
        ("testParsePacketFromIncorrectResponseData", testParsePacketFromIncorrectResponseData),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(StunClientIntegrationTests.__allTests__StunClientIntegrationTests),
        testCase(StunMessageTypeTests.__allTests__StunMessageTypeTests),
        testCase(StunPacketTests.__allTests__StunPacketTests),
    ]
}
#endif
